### ISSUE TITLE
Käyttäjä voi lisätä lukuvinkin jolla otsikko ja linkki

### ISSUE THREAD

**Issue by PaulusParssinen** [PaulusParssinen/ohtu-miniprojekti#1]
Käyttäjä voi lisätä sovellukseen lukuvinkin jolla on otsikko ja linkki. Käyttäjä lisää lukuvinkin käyttäen tekstipohjaista terminaali käyttöliittymää. Lukuvinkit tallenetaan pysyväistalletukseen paikalliseen tietokantaan.

## Tasks
* [x] Lukuvinkeille luodaan luokka (riikka)
* [x] Lukuvinkeille on luotu oma taulu tietokantaan
    * [ ] Lukuvinkit säilyvät sovelluksen uudelleenkäynnistyksen yli
* [ ] Lukuvinkin voi lisätä käyttöliittymällä
* [ ] Lukuvinkki luokalla on yksikkötestit (riikka)
* [ ] Lukuvinkin lisäämiselle on toteutettu hyväksymiskriteerien testaus Robot Frameworkilla
